server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.184.130:3306/flowable?nullCatalogMeansCurrent=true&serverTimezone=GMT%2B8
    username: root
    password: 222222
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yorkhean.flowable.entity
logging:
  level:
    ccom.yorkhean.flowable: debug
flowable:
  database-schema: flowable
  check-process-definitions: false
  database-schema-update: false

